### PR TITLE
Separated routes and controlling function from app

### PR DESCRIPTION
**Pull request by E-Kemp**

### CODE REVIEW

**Comment by E-Kemp** [comment]
I've just realised I should add redirects for previous routes so client doesn't break instantly!

**Review by nlisgo — DISMISSED** [review]
LGTM

**Comment by nlisgo** [comment]
> I've just realised I should add redirects for previous routes so client doesn't break instantly!

@E-Kemp Maybe add a comment in the PR description. Or add a comment on the code. Say what you said on the call we had.

**Review by scottaubrey — CHANGES_REQUESTED** [review]
I've got one biggie that I think needs to block this for now.

My other comment is that most of this code will disappear (in theory, only the preprints-controller/routes stays). Most of this reorganisation will look strange when there is only one controller + base controller left. It will mek surgencally removing all that easy though I guess. :)

**Review by scottaubrey — APPROVED** [review]

**Pull request merged**
