### PR TITLE
Switch reviews to using data-hub docmaps

### PR DESCRIPTION
**Pull request by scottaubrey**
reworking any assumptions about docmap parsing

### CODE REVIEW

**Comment by HazalCiplak** [comment]
The `author-response` part has been added to the Data Hub Docmaps API response, so if that was the only thing blocking this ticket, it should be resolved now. If there is anything else I can do for you, please let me know.

**Review by E-Kemp — COMMENTED** [review]
I've taken a good look into the new method of fetching the Docmaps, and I'm happy with this to be merged, however I'd first like to have a quick sanity check with Scott about the expected behaviour of the reviewed-preprints endpoints.

**Comment by scottaubrey** [comment]
> The `author-response` part has been added to the Data Hub Docmaps API response, so if that was the only thing blocking this ticket, it should be resolved now. If there is anything else I can do for you, please let me know.

@HazalCiplak  

Actually, this ticket was the biggest blocker I had noticed: https://github.com/elifesciences/data-hub-issues/issues/612

If you're able to take a look at that one at some point soon, that would be great. Please let me know if not though, Thanks!

**Comment by HazalCiplak** [comment]
> Actually, this ticket was the biggest blocker I had noticed: https://github.com/elifesciences/data-hub-issues/issues/612

I wasn’t aware of this issue, I've added it into Data Hub board and will try to have look into this today

**Comment by QueenKraken** [comment]
This ticket was in review but moved to backlog so we can focus on clearing other work which will free up the team to support this task.

**Review by will-byrne — APPROVED** [review]

**Comment by QueenKraken** [comment]
Blocked while DataHub resolve missing data (WIP)

**Pull request merged**
