### PR TITLE
Prevented renovate from auto-merging to master

### PR DESCRIPTION
**Pull request by E-Kemp**

### CODE REVIEW

**Comment by nlisgo** [comment]
Followup PR to fix issue that is caused by the recent renovate automerges: https://github.com/elifesciences/enhanced-preprints-server/pull/604

**Review by nlisgo — APPROVED** [review]
We should disable automerge until we have improved the tests. We should consider disabling automerge for other repo's until we have an improved level of test coverage.

**Comment by scottaubrey** [comment]
> We should disable automerge until we have improved the tests. We should consider disabling automerge for other repo's until we have an improved level of test coverage.

This was a build failure, not a test failure:
- Renovate responded to a node version release and maintains the tag suffix (in this case, the alpine version) because that's what you should do in the crazy world of docker versioning.
- In the meantime, somewhere between node 16.18-16.19, the alpine version fell out of support 
- node don't release images for out-of-support OS image.
support).

The result is that docker can't build the image because the tag doesn't exist. If it did, it would mostly likely build fine.

What we should do to "test" for this is build the docker image in all PRs, but that will add more time to all PRs.

**Comment by nlisgo** [comment]
@scottaubrey I agree. I think we should expand the tests to include a build run.

https://github.com/elifesciences/enhanced-preprints-server/pull/605

**Comment by nlisgo** [comment]
I did toy with the idea to only test the build if there are changes to the Dockerfile.

**Pull request merged**
